# Server configuration
server:
  port: "8080"
  environment: "development"
  allow_origins: "*"
  read_timeout: "5s"
  write_timeout: "10s"
  idle_timeout: "120s"

# JWT configuration
jwt:
  secret:
    value: "ENC[2mcF/wwb8wk9M6bIaVfXCxdys0Zkeby4qErkVLzTcltp+3I6Q0VvH+gHydfdwe]"
  token_lifetime: "24h"
  issuer: "passless-auth"

# Security configuration
security:
  max_login_attempts: 3
  lockout_duration: "15m"
  otp_length: 6
  otp_expiry: "5m"
  rate_limit:
    requests_per_minute: 20
    burst_size: 5
  two_factor:
    enabled: true
    issuer: "Passless Auth"
    algorithm: "SHA1"
    digits: 6
    period: 30
    skew: 1

# Redis configuration
redis:
  host: "redis"
  port: "6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  key_prefix: "passless:"
  ttl:
    twofa_secret: "24h"
    twofa_attempts: "5m"

# SMS configuration
sms:
  provider: "twilio"
  account_sid:
    value: "ENC[gonVCTcByr2ZgHnMwiQ9z/gpFP6PrsYezwdAdvTdGcu3Vub9vmRWByBL2TJWJRHDfRpo=]"
  auth_token:
    value: "ENC[gGlFQlCkvQD6AkjfozUER3/4biT1Wjlljd+AnT7s7eWMAOiQdktQZEvy6g2dnF6c7tJGt/jz]"
  from_number: "+16052504547"
  template_id: ""

# Logging configuration
logging:
  level: "info"
  format: "json"
  output_path: ""

# Metrics configuration
metrics:
  enabled: true
  port: "9090"
  path: "/metrics"

# Tracing configuration
tracing:
  enabled: true
  service_name: "passless-auth"
  endpoint: "http://localhost:4317" 